In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np
import pickle
import cv2, os
from glob import glob
from keras.utils.np_utils import to_categorical

In [2]:
def get_image_size():
	img = cv2.imread('gestures1/1/100.jpg', 0)
	return img.shape

def get_num_of_classes():
	return len(glob('gestures1/*'))

image_x, image_y = get_image_size()
image_x

256

In [28]:
with open("train_images", "rb") as f:
    train_images = np.array(pickle.load(f))
with open("train_labels", "rb") as f:
    train_labels = np.array(pickle.load(f), dtype=np.int32)

with open("test_images", "rb") as f:
        test_images = np.array(pickle.load(f))
with open("test_labels", "rb") as f:
        test_labels = np.array(pickle.load(f), dtype=np.int32)

train_images = np.reshape(train_images, (train_images.shape[0], image_x, image_y, 1))
test_images = np.reshape(test_images, (test_images.shape[0], image_x, image_y, 1))
train_labels = tf.keras.utils.to_categorical(train_labels)
test_labels = tf.keras.utils.to_categorical(test_labels)

print(train_labels[0])

print(train_labels[1])

print(train_labels[2])

print(train_labels[3])
print(test_images.shape)

[0. 0. 0. 1.]
[0. 0. 0. 1.]
[0. 0. 1. 0.]
[0. 0. 0. 1.]
(60, 256, 256, 1)


In [19]:
model = tf.keras.models.Sequential([
  
  tf.keras.layers.Conv2D(16, (2,2), input_shape=(256, 256, 1), activation='relu'),
  tf.keras.layers.MaxPooling2D(pool_size=(2, 2), strides=(2, 2), padding='same'),
  tf.keras.layers.Conv2D(32, (3,3), activation='relu'),
  tf.keras.layers.MaxPooling2D(pool_size=(3, 3), strides=(3, 3), padding='same'),
  tf.keras.layers.Conv2D(64, (5,5), activation='relu'),
  tf.keras.layers.MaxPooling2D(pool_size=(5, 5), strides=(5, 5), padding='same'),
  tf.keras.layers.Flatten(),
  tf.keras.layers.Dense(32, activation='relu'),
  tf.keras.layers.Dense(4, activation='softmax')
    

])



In [20]:
model.compile(loss='categorical_crossentropy', metrics=['accuracy'])


model.fit(train_images, train_labels, epochs=1)
model.evaluate(test_images, test_labels)

classifications = model.predict(test_images)

2/2 [==============================] - 0s 105ms/step - loss: 8.9546e-04 - accuracy: 1.0000


In [21]:
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(test_acc)

2/2 [==============================] - 0s 109ms/step - loss: 8.9546e-04 - accuracy: 1.0000
1.0


In [22]:
print(classifications)

[[1.11718393e-04 9.98602927e-01 1.64654950e-04 1.12075720e-03]
 [1.38710802e-05 9.99702275e-01 5.65982955e-05 2.27221826e-04]
 [1.52468949e-03 3.98833916e-04 1.17383039e-04 9.97959137e-01]
 [1.26365834e-04 9.98479426e-01 7.10499065e-04 6.83674007e-04]
 [5.90035459e-04 1.07841952e-04 3.04951918e-05 9.99271691e-01]
 [1.63093428e-04 1.24257053e-06 9.99821961e-01 1.36773851e-05]
 [1.93643558e-04 2.90934418e-06 9.99788821e-01 1.46649372e-05]
 [1.05132342e-04 9.98824894e-01 1.99797258e-04 8.70196964e-04]
 [3.59149242e-04 2.94424990e-06 9.99606431e-01 3.15063662e-05]
 [3.16963095e-04 9.98607934e-01 4.88424150e-04 5.86684968e-04]
 [5.84431327e-05 9.99043167e-01 1.46470920e-04 7.51864922e-04]
 [6.60843070e-05 9.99490023e-01 1.15961098e-04 3.27933958e-04]
 [1.20045224e-04 1.57167028e-06 9.99870539e-01 7.86903092e-06]
 [2.32874518e-05 9.99514699e-01 7.80114933e-05 3.83996841e-04]
 [1.53346767e-03 4.33967129e-04 1.74618166e-04 9.97857988e-01]
 [1.16979703e-04 9.40603059e-07 9.99868989e-01 1.315148